### ISSUE TITLE
Error: I could not connect to Yahoo's servers

### ISSUE THREAD

**Issue by bryan-farris** [landonp1203/yahoo-fantasy-bot#20]
This morning the bot returned 20+ of these messages. Is this related to an incorrect configuration somewhere? We had previously received a few successful updates through the bot.

Screenshot: https://cl.ly/d97cb159e5ed

Thanks in advance, super excited to use the bot for our league this year!

**Comment by malf922** [comment]
I had the same message, many times, but then I got a transaction alert in real time, just a couple hours after the last error message. I assumed changes were made so I re-deployed the app.

**Comment by bryan-farris** [comment]
@malf922 I figured that might be the case too. Am I reading the instructions correctly, that a "re-deploy" includes basically deploying a new instance of the app? Or am I missing something?

**Comment by malf922** [comment]
@bryan-farris correct. I just went through the setup process again. I would hold off though, as it appears Landon is working on another release as we speak, which will be out today. (per his last message on my Issue post).

**Comment by landonp1203** [comment]
Latest update should be up, nuke the old one, and redeploy and it should work now.

**Comment by brucebarnes** [comment]
Had same issue.  When we delete app and redeploy, do we need to change the names of the bot to make it work?  Also is there a test to see if it is working?

**Comment by landonp1203** [comment]
No, you do not need to change the name.  If you do change the name, you will have to redo the yahoo api part since it points to the app-name.heroku.com url, which would change if the bot name changes.  The test should be that it sends a message to your group.  As of now, that is the only way to determine if it is working.  You can also check the Heroku logs by going to the `More` button and click `View Logs` to see it working.

**Comment by bryan-farris** [comment]
> Latest update should be up, nuke the old one, and redeploy and it should work now. @bryan-farris

@landonp1203 thanks for the quick feedback. Unfortunately after nuking my previous app and redeploying, I'm getting an Application Error on Heroku when trying to Open the App (last few steps after adding the Config Vars): https://cl.ly/37b71a739fe4

Any thoughts?

**Comment by bryan-farris** [comment]
Nevermind, I think I figured it out! Had to turn on the `bot` Dyno to authorize.

**Comment by landonp1203** [comment]
All good!  Please redeploy once again, there was a null pointer exception that was thrown in the standings update.  The update fixes it. @bryan-farris @malf922 @brucebarnes @DMcP89
