### ISSUE TITLE
Add player profile pictures

### ISSUE THREAD

**Issue by tonycchung** [landonp1203/yahoo-fantasy-bot#25]
Not really an issue as much as a suggestion - it'd be awesome if you could use the nfl api to add player profile pictures in transaction updates

https://api.nfl.com/docs/endpoints/profilePicture/index.html?sp-cl-mc-af-pj=&source=pepperjam&publisherId=96525&clickId=2817513345

I'd love to contribute but I'm a ruby/go guy with zero familiarity with kotlin/gradle though I'm willing to take a stab and open a PR at some point.

**Comment by landonp1203** [comment]
If you've ever worked with Java, its pretty much the same language with some functional programming semantics thrown in which are very powerful.

I'd love for you to contribute and add this!

**Comment by tonycchung** [comment]
cool, will try to take a crack at this in the next week or two when ive got time, thanks!

awesome project btw, really looking forward to it!

**Comment by landonp1203** [comment]
Closing since no updates nor is it a feature I am willing to work on since it is very niche.  If anyone would like to work on this, feel free.
