### ISSUE TITLE
User reports bot not sending messages after score update on Monday

### ISSUE THREAD

**Issue by landonp1203** [landonp1203/yahoo-fantasy-bot#34]
Users has reported that they got all messages up until standings, and then have not gotten any transaction messages afterwords.  As per conversation, there seems to something wrong with standings even though the have FAAB in their league.

Will investigate further.

**Comment by bryan-farris** [comment]
Hey @landonp1203, don't mean to piggyback here and if you'd prefer an alternate form of communication, let me know. I just wanted to chime in and say that the only updates we're getting (from Yahoo > Slack) are add/drops. Do I need to update anything to include scores/standings?

**Comment by landonp1203** [comment]
This is the perfect communication, allows me to track issues better then reddit.

Do you have a FAAB league by chance?  I’m going to break off a desperate branch and test the standings since I also noticed my league didn’t get the notification either.

And never apologize especially for issues I created!

**Comment by MusiclMike51** [comment]
I also have only received adds/drops and commissioner changes.
This is not a FAAB league just a normal waiver league.
Bot method - Discord Webhook

**Comment by bryan-farris** [comment]
No ours is just standard waiver, not FAAB

**Comment by landonp1203** [comment]
Yep, okay I think I’ve pinpointed without even looking at the code.  The standings will throw the same FAAB error if FAAB does not exist.  Relates to #32.

**Comment by landonp1203** [comment]
#29 fixed this in matchups, but was caught in standings afterwords.

**Comment by bryan-farris** [comment]
I'll keep my eyes open.

**Comment by landonp1203** [comment]
Should be fixed because of 86039c9c68fb6acb75c4d76316114161a84d5932
