### ISSUE TITLE
Add/drop activity for one owner not appearing

### ISSUE THREAD

**Issue by ap4open** [landonp1203/yahoo-fantasy-bot#36]
Not enough information to tell for sure, but I see slack messages from the bot for 8 other members, and 1 person in the league has not made any player transactions. I've made 2 add/drop transactions, and do not see a corresponding slack message. The yahoo api key was made using my yahoo account - could that play a factor?

**Comment by ap4open** [comment]
We have differences in scoring settings and starting roster requirements, but don't think that would impact this issue. I can try changing my team name to see if that changes anything.

**Comment by landonp1203** [comment]
If you think that could fix the issue, I’m all for it!  Haven’t had a chance to look since I’m at work, but will do tonight!

**Comment by landonp1203** [comment]
Do you have an update on this? @ap4open

**Comment by ap4open** [comment]
Sorry, I've updated my team name, but have not made any transactions yet. Hoping tomorrow's scoring updates will give more info. Incidentally, are you using any particular type of logging, or just the default heroku?

**Comment by landonp1203** [comment]
Heroku...only logs when you started looking at the logs which is annoying

**Comment by ap4open** [comment]
Update: received score alert at the start of Sunday's early games. I had changed my team name to use 2 backslashes, and it displays as only one. Another observation: the official yahoo app displays my team name with only 1 backslash. This leads me to suspect that perhaps the issue is with the yahoo api.

**Comment by landonp1203** [comment]
Yah so it looks like there's an escape character issue going on with your name, but it still doesn't explain why add/drops aren't happening for that team tho.

**Comment by ap4open** [comment]
Update: Waiver period ended this morning, and it looks like no add/drops are being reported by the bot. I suspect this is related to issue #40.

**Comment by landonp1203** [comment]
Yep thinking its a collapsed stream, shut the bot dyno off and turn it back on again as a temporary fix.

**Comment by landonp1203** [comment]
Closing as fixed in later updates as well as no further updates.
