### ISSUE TITLE
Add contributor guide

### ISSUE THREAD

**Issue by red-scott** [landonp1203/yahoo-fantasy-bot#39]
Would love a brief document on how to contribute.

From your comments I figured out to download IntelliJ and open the project with the "gradle". I spent a few hours on it yesterday and couldn't figure how to get the tests to run. Any details there would be helpful.

**Comment by landonp1203** [comment]
So it looks like I broke the tests, I need to set them up a certain way in the project structure and I did not do that, let me fix that first.

**Comment by landonp1203** [comment]
I will be able to add the contributor guide tomorrow when I get back from my vacation...but it should now work in IntelliJ, you should see a green "plus" button next to the test functions.

If you are having issues, navigate to the following `Settings > Build,Execution,Deployment > Build Tools > Gradle > Runner > "Run tests using:` and change it to `IntellIJ for both dropdown and it should work.  IntelliJ 2019.2 broke testing by changing settings.

**Comment by landonp1203** [comment]
If someone wants to add this, feel free.  But using this issue and knowing how to add the project into your IDE is more than enough.
