### ISSUE TITLE
Feature Request: Ability to toggle each alert by type and time

### ISSUE THREAD

**Issue by krasher134** [landonp1203/yahoo-fantasy-bot#43]
I'd love the ability to enable and disable certain alerts for my league.

My league isn't as active as others, and because of the sheer number of alerts the bot sends, we basically have ended up using GroupMe as a notification system and nothing more. That also means that we receive "Score Alerts" Thursday night after the game and then Sunday morning before the games that are essentially the same and unnecessary.

I would like to experiment with only offering add/drop alerts and maybe close match-up alerts to see if that helps with league engagement, as the bot seems to dominate conversation at the moment.

**Comment by krasher134** [comment]
Figured out how to make these changes myself in the Arbiter.kt file.

**Comment by GlicketySplit** [comment]
@krasher134 How were you able to do this?
