### ISSUE TITLE
No score updates

### ISSUE THREAD

**Issue by scottillogical** [landonp1203/yahoo-fantasy-bot#45]
Thanks for this project!

According to the readme, score updates are supposed to be sent at out but they don't appear to be being sent out for me - so far since I installed it earlier this week, it has only posted add/drop and trade messages

Is this because the score update jobs are commented? https://github.com/landonp1203/yahoo-fantasy-bot/blob/master/bot/src/main/kotlin/bot/utils/Arbiter.kt#L113

**Comment by scottillogical** [comment]
Was it commented because it was too noisy? If so that's cool with me

**Comment by landonp1203** [comment]
12c52ab should fix this
