### ISSUE TITLE
OAuth failed on starting app

### ISSUE THREAD

**Issue by lammypham** [landonp1203/yahoo-fantasy-bot#46]
After adding all the config envs and opening the application i ran into an OAuth issue
I also happen to not own the league as well, not sure if this is causing the problem or not.

Build process for heroku seemed to worked fine as well.

**Comment by landonp1203** [comment]
Delete the bot and retry, it sounds like a config issue.  Or it could be that Yahoo's servers are down, which has happened to me before.

**Comment by landonp1203** [comment]
Didn't hear anything about this, closed.
