### ISSUE TITLE
Interested in trying this out for MLB. 

### ISSUE THREAD

**Issue by EffDub** [landonp1203/yahoo-fantasy-bot#51]
Hello,

I'm looking at integrating this into a slack channel in my org for MLB fantasy.  I'm a bit of noob when it comes to coding.

I've been reviewing this code, and it looks like it should work well for Yahoo MLB.  

It appears from the code I can easily do the following:

- modify existing NBA, NFL, and 'football' references to MLB, and 'baseball'.
- Yahoo auth and league configs appear to be accurate, so nothing special there either.

I guess what I can't seem to identify is where to have the bot updates scores.  (I'll be using this to go to a slack channel).

- Can this be daily?  Or multiple times per day?  If so, where to modify?

Thanks for the assist!

**Comment by WhosNickDoglio** [comment]
Hey @EffDub 

Check out [my fork](https://github.com/WhosNickDoglio/yahoo-fantasy-bot) to support other fantasy sports.  I currently use it for my NBA fantasy league but imagine it would work for MLB as well. Just enter mlb as the game key during the setup. 

> I guess what I can't seem to identify is where to have the bot updates scores. (I'll be using this to go to a slack channel).
>  - Can this be daily? Or multiple times per day? If so, where to modify?

I'm an Android developer so _maybe I'm wrong_ but I believe this is handled in the `Arbiter` class in the following method:

https://github.com/landonp1203/yahoo-fantasy-bot/blob/12c52ab00c047891f954e215291a074223e01693/bot/src/main/kotlin/bot/utils/Arbiter.kt#L103-L113

I imagine adding new `Jobs` with whatever schedule you would want here would do the trick but I haven't been able to test it with all the leagues being suspended.  

Hope this helps!

**Comment by landonp1203** [comment]
https://github.com/landonp1203/yahoo-fantasy-bot/pull/50 allows this :)  Closing.
