### ISSUE TITLE
Need to use GroupMe?

### ISSUE THREAD

**Issue by Hop-Poppa** [landonp1203/yahoo-fantasy-bot#54]
I am trying to get the bot for a discord server. I believe all my information was entered correctly and I left the GroupMe and Slack variables empty. When I click open App I get the following:

![image](https://user-images.githubusercontent.com/66859287/84559866-60d7b080-acf3-11ea-9190-eca60bc592f5.png)

**Comment by Hop-Poppa** [comment]
I think I found the issue, you have t have something filled in (even if its random forehead to keyboard strokes) because it isn't optional.
https://github.com/landonp1203/yahoo-fantasy-bot/blob/b3f1d01179a2da7ff681715600184a92dd5d8829/shared/src/main/kotlin/shared/EnvVariablesChecker.kt?fbclid=IwAR2K6iAyvzb1wK2ASGIKgmAct51yPAPqmcs27GK8vRbMojqsVFuqH9ac54w#L21

**Comment by landonp1203** [comment]
Thanks for catching this, I will fix this.
