### ISSUE TITLE
Yahoo Game Key

### ISSUE THREAD

**Issue by Incogneat01234** [landonp1203/yahoo-fantasy-bot#57]
Does anyone know the latest game key for the 2020 fantasy football season. I cannot seem to find it.

**Comment by Incogneat01234** [comment]
399

**Comment by landonp1203** [comment]
I wonder if there is a way I can grab the latest key automatically, thus that is one less thing the users have to configure...

**Comment by Incogneat01234** [comment]
There appear to be a few apps here on GitHub which may be doing the same thing. Last year it was 390, so I simply just queried the API at 391, 392, etc until it returned that the game was 2020 football, full.

**Comment by landonp1203** [comment]
They are automatically configuring?  Or they have the same issue as mine?  Its pretty annoying that you even had to do that, I'm sorry about that.

**Comment by Incogneat01234** [comment]
Ah, sorry I wasn't clear. They are auto configuring. Seems like it's a query that can be run through the yahoo API, but I didn't dig too deep into it.

**Comment by landonp1203** [comment]
Looks like I found the API to do it: https://developer.yahoo.com/fantasysports/guide/#sample-xml

**Comment by Incogneat01234** [comment]
Perfect! Thanks for the bot, we just switched to discord and implemented it and my league thinks it's fantastic.

**Comment by landonp1203** [comment]
Awesome!  I'm really glad, maybe tomorrow I'll have the fix out.  Work has me swamped, so we will see.

**Comment by landonp1203** [comment]
@Incogneat01234 Added the auto config for game key, tell me if it makes it easier for you.  Thanks for telling me about it!

**Comment by scottillogical** [comment]
Updating my heroku app this year, getting this error
```2020-09-10T16:34:00.146097+00:00 app[bot.1]: Exception in thread "main" exceptions.EnvVariableException: Environment variable shared.EnvVariable$Str$YahooGameKey@76ed5528 was not entered correctly.  Please fix and restart dynos.
2020-09-10T16:34:00.146303+00:00 app[bot.1]: at shared.EnvVariablesChecker.checkString(EnvVariablesChecker.kt:31)```
Not sure if the auto config is working - I'll add it manually, assuming that works

**Comment by LandonPatmore** [comment]
@scottillogical I got an email about your issue, but looks like you deleted your comment.  Was the issue resolved?

**Comment by scottillogical** [comment]
@LandonPatmore yep! i got an error asking for a gamekey, resolved it by adding GameKey MLB env var

**Comment by LandonPatmore** [comment]
Is it working for MLB? I am curious now @scottillogical

**Comment by scottillogical** [comment]
working so far for me

**Comment by LandonPatmore** [comment]
Awesome! If you have any issues, please create an issue so I can track it...nice to know that its working in other types of fantasy leagues as well!
